{
 "title": "JVM Overview (OpenTelemetry)-2",
 "description": "Dashboard for JVM metrics with OpenTelemetry instrumentation",
 "tags": [
  "JVM",
  "open-telemetry",
  "Java",
  "otel",
  "opentelemetry",
  "otlp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "HTTP server request rate",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4XX %",
   "type": "timeseries",
   "description": "HTTP server error ratio - ratio of requests that return 5xx",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance)(rate(http_server_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\", http_status_code=~\"4.*\"}[$__rate_interval]))) / on (instance) (sum by (instance)(rate(http_server_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "HTTP server request duration",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance)(rate(http_server_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))) / \non (instance) \n(sum by (instance)(rate(http_server_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for the whole system",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_utilization_ratio{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory utilization",
   "type": "timeseries",
   "description": "Used heap memory / heap memory limit ",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (process_runtime_jvm_memory_usage_bytes{job=~\"$job\",type=\"heap\", instance=~\"$instance\"}) / on (instance) \nsum by (instance) (process_runtime_jvm_memory_limit_bytes{job=~\"$job\",type=\"heap\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - used"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "Percentage of time spend for garbage collection pauses",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(process_runtime_jvm_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "timeseries",
   "description": "Number of currently loaded classes",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_classes_current_loaded{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of currently executing (also called \"live\") threads",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_threads_count{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}