apiVersion: apps/v1
kind: Deployment
metadata:
  name: person
  namespace: elb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person
  template:
    metadata:
      labels:
        app: person
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
        prometheus.io/path: /
    spec:
      containers:
        - name: person
          image: 970662323538.dkr.ecr.us-east-1.amazonaws.com/person:latest
          ports:
            - name: tcp
              containerPort: 8080